Feature database
PSW-2020-ORG9/HealthcareIS pull request #5
Opened 2020-11-02 23:06 UTC by nikolagudelj

2020-11-02 23:39 UTC, nikolagudelj commented
![](https://github.trello.services/images/mini-trello-icon.png) [[E0.2] Replace Json storage with SQL [8]](https://trello.com/c/hPZ8rEAP/13-e02-replace-json-storage-with-sql-8)

2020-11-03 09:11 UTC, FmasterofU commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR Feature Database](https://trello.com/c/wHj4Yhoi/49-pr-feature-database)

2020-11-03 09:13 UTC, FmasterofU requested changes
Secrets must not be present in source code!
Your options are to use Environment Variables, Secret Manager(better), Azure Key Vault(I'm not sure how this works, but that could be the best option) ...
Make sure to use a different DB password after this and a sincere advice is to never use this password again, anywhere, since it's been posted online.
Please ask, and do expect help from @PSW-2020-ORG9/devops team in resolving this issue.

2020-11-03 09:13 UTC, FmasterofU commented on HealthcareBase/Model/Database/MySqlContext.cs
> +        private static string password = "chc6kcxhd";
Hell no.

2020-11-04 10:14 UTC, FmasterofU approved these changes
Secret (db conn) issue delegated to ASP.NET(+base dll) project.

2020-11-04 10:38 UTC, hi-imAndy approved these changes

2020-11-04 10:40 UTC, rammba approved these changes

2020-11-04 10:41 UTC, merged

2020-11-09 19:25 UTC, hi-imAndy commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR Feature database](https://trello.com/c/3TQYSdRf/58-pr-feature-database)