End of Sprint - Disable permissions for Devs
PSW-2020-ORG9/HealthcareIS pull request #6
Opened 2020-11-03 11:23 UTC by FmasterofU

Automatic (scheduled pipeline) update @PSW-2020-ORG9/developers permissions to **Read** on end of sprint - Even week 12AM Mon UTC+1

2020-11-03 11:32 UTC, FmasterofU commented
![](https://github.trello.services/images/mini-trello-icon.png) [(4) Configure scheduled jobs for managing developers team access to GitHub repository](https://trello.com/c/tRbm8Vm1/48-4-configure-scheduled-jobs-for-managing-developers-team-access-to-github-repository)

2020-11-03 11:44 UTC, rammba approved these changes

2020-11-03 15:12 UTC, rammba requested changes
Correct execution per UTC time

2020-11-03 17:08 UTC, rammba approved these changes

2020-11-03 17:25 UTC, BoKna031 approved these changes

2020-11-03 17:32 UTC, merged

2020-11-09 19:40 UTC, hi-imAndy commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR End of Sprint - Disable permissions for Devs](https://trello.com/c/AUtgkFd3/61-pr-end-of-sprint-disable-permissions-for-devs)